name: Exemplo de Limpeza de Contêineres

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa semanalmente à meia-noite de domingo
  workflow_dispatch:     # Permite execução manual

jobs:
  cleanup-containers:
    name: Limpar contêineres antigos
    uses: softo-develop/ghrc-prune@main
    with:
      token: ${{ steps.token-step.outputs.token }}
      organization: ${{ steps.repo_owner_name.outputs.repo_owner_name }}
      days_old: 0
      keep_latest_count: 2